name: 'Deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push frontend to dokku
        uses: obrassard/action-dokku-deploy@v1.0.2
        with:
          dokku_repo: 'ssh://dokku@git.birdup.link/ai-tunnel-frontend'
          ssh_key: ${{ secrets.SSH_KEY }}
          deploy_branch: 'main'

      - name: Push backend to dokku
        uses: obrassard/action-dokku-deploy@v1.0.2
        with:
          dokku_repo: 'ssh://dokku@git.birdup.link/ai-tunnel-backend'
          ssh_key: ${{ secrets.SSH_KEY }}
          deploy_branch: 'main'
